### ISSUE TITLE
Question about how to use this

### ISSUE THREAD

**Issue by KevinNitroG** [nikhilbadyal/ghaction-telegram-uploader#25]
Hi, I just want to know where to take changelog github repo from? I have filled in `https://github.com/inotia00/revanced-patches` But in Telegram, the message show no changelog. Do I misunderstand about changelog github repo?
```
  CHANGELOG_GITHUB_REPOSITORY:
    required: false
    description: 'Repo to Fetch Changelog'
```
Here is the picture of message in Telegram
![image](https://user-images.githubusercontent.com/86353526/229570718-1bc5eaba-2737-4bc8-814e-d9bf7911ae72.png)

**Comment by KevinNitroG** [comment]
This is the code in my github action yml

```
Upload_to_Telegram_KevinNitro:
    uses: nikhilbadyal/ghactions/.github/workflows/telegram-uploader.yml@main
    needs: Build_APK
    secrets:
      TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
      TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      CHANGELOG_GITHUB_REPOSITORY: https://github.com/inotia00/revanced-patches
```
